apiVersion: v1
kind: Service
metadata:
  name: registration-app-service
  namespace: default
  labels:
    app: registration-app
spec:
  type: NodePort
  selector:
    app: registration-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30007
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  name: registration-app-lb
  namespace: default
  labels:
    app: registration-app
spec:
  type: LoadBalancer
  selector:
    app: registration-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5000
